### ISSUE TITLE
Function not recognizing container width?

### ISSUE THREAD

**Issue by stevenspiel** [jquery-textfill/jquery-textfill#31]
I have some interesting behavior where I call this function in a `document.ready`:

``` js
$(document).ready(
    $('h2#name').textfill({
        widthOnly: true, 
        maxFontPixels: 25, 
        minFontPixels: 4
    })
)
```

I know it is doing something because the `white-space:nowrap;` is being added, and the `maxFontPixels`  of `25px` is also being added as an inline element. But it is not adjusting the font size to my container width.

Then when I run the same command in my console (chrome, this time without the `document.ready()`), the font then changes to fit the container.

The container looks like this:

``` html
<h2 id="name">
  <span>Looooooong Name</span>
</h2>
```

And the css is like this:

``` css
#name {
  margin: 0;
  font-weight: normal;
  font-size: 27px;
  width: 100px;
  line-height: 31px;
  vertical-align: middle;
}
```

So, is the width of the element not being recognized until after the page loads?
